### ISSUE TITLE
Autoconf error

### ISSUE THREAD

**Issue by khoegenauer** [bcthomas/pullseq#2]
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

When run manually, it creates the configure file, as expected; however, I am writing a script to include your software in the homebrew package management system, and this error causes the script to terminate (abort the install).

It may be worth adding the need to run autoconf into the documentation, as the 1.0.0 tarball does not include the generated configure file.

**Comment by bcthomas** [comment]
OK - updated docs to include an autoconf step when using github-created releases. Also updated to a new version with an important bug fixed. Thanks!
