### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by ctekellogg** [bcthomas/pullseq#3]
Hi,
I am trying to file a MiSeq Index file based on a set of headers using the following command:

pullseq -i HallS-pool_S1_L001_I1_001.fastq -n IDs.txt -v > barcodes.fastq 

This is the read out as pullseq is running:

verbose flag is set
Input is HallS-pool_S1_L001_I1_001.fastq
Names in IDs.txt will be included
Output will be 50 columns long

done reading from input (19467839 entries)
Input is FASTQ format
Processed 0 entries
Pulled 0 entries

Why might this be happening? Here is any example of the index fastq file:
@M00366:86:000000000-AJP15:1:1101:18035:1000 1:N:0:1
ATAGGAATAACC
+
CCCCCGGGGGCD
@M00366:86:000000000-AJP15:1:1101:14066:1000 1:N:0:1
GTGAGGTTCGGC
+
6A--6C@,C++F
@M00366:86:000000000-AJP15:1:1101:14848:1000 1:N:0:1
ATAATTGCCGAG
+
CCCCCGGGGGGG
@M00366:86:000000000-AJP15:1:1101:18086:1000 1:N:0:1
TCTCTACAAGTA
+
8----;-,--;-
@M00366:86:000000000-AJP15:1:1101:16316:1000 1:N:0:1

Here is what the IDs.txt file looks like:
@M00366:86:000000000-AJP15:1:1101:18846:1146 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:17470:1146 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:18794:1147 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:9220:1147 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:9734:1147 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:12133:1147 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:17621:1148 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:20761:1148 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:11504:1148 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:19907:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:17935:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:17274:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:10546:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:13379:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:16248:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:13417:1149 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:11550:1150 1:N:0:1
@M00366:86:000000000-AJP15:1:1101:16087:1150 1:N:0:1

Is this structured okay? Why might no output be generated?  I've been searching all over for a tool like this and I was hoping this would do the trick. I hope I can get this to work.

Thank you for your help,
Colleen

**Comment by bcthomas** [comment]
Hi Colleen,

(Sorry but I've been traveling and didn't see this notification)

Everything looks fine with your command line usage. The only thing I can think of is that your list of names (IDs.txt) doesn't actually have any of the reads in the read files you're trying to extract from?  Could you check that first (perhaps using grep, like so...

```
grep -c 'M00366:86:000000000-AJP15:1:1101:18846:1146' HallS-pool_S1_L001_I1_001.fastq
```

**Comment by bcthomas** [comment]
Closing this until we have further input...
