### ISSUE TITLE
Port to pcre2?

### ISSUE THREAD

**Issue by nileshpatra** [bcthomas/pullseq#8]
Hi @bcthomas 

Thanks for your work on pullseq. I maintain pullseq in Debian, and we are now in the process of removing pcre (which is unmaintained for several years) hence, could you please port the code to the newer pcre2?

Regards,
Nilesh

**Comment by bcthomas** [comment]
hi Nilesh - I just created a branch called pcre2 and ported it to specifically use pcre2. Could you test it out?

**Comment by nileshpatra** [comment]
Hi @bcthomas this works great, and the package tests at my end pass as well. Could you please merge the branch to master, and make a new patch release?
That'd be very helpful

**Comment by bcthomas** [comment]
done - i created a branch (oldpcre) that supports v1 of the PCRE library. don't know if this is proper way to handle supporting two library dependencies or not. Closing issue for now.
