### ISSUE TITLE
Updating CFLAGS variable doesn't solve error during configuration

### ISSUE THREAD

**Issue by ochkalova** [bcthomas/pullseq#9]
Hi, 
while running `./configure` I've got message about absent `libpcre2`. I've installed it with conda:
```
>conda install -c anaconda pcre2
```
And updated CFLAGS variable as described in  README:
```
> pcre-config --cflags
-I/home/sochkalova/miniconda3/envs/das_tool/include
>export CFLAGS="-I/home/sochkalova/miniconda3/envs/das_tool/include"
>./configure
```
That gave me the same message about not installed `libpcre2`. I don't understand what to do. Can you please help?

P.S. I work on the server where I don't have access to `sudo`(just in case)

**Comment by bcthomas** [comment]
Hi and sorry you’re having trouble.  Could you try updating flags with the output from pcre2-config, not pare-config?
